source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

target 'Vipect_Example' do
  pod 'Vipect', :path => '../'
  pod 'RxSwift', '~> 6.0'
  pod 'RxCocoa', '~> 6.0'

  target 'Vipect_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 3.0.0'
    pod 'Nimble', '~> 9.0.0'
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
    
    project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end
end
