//
//  SimpleView.swift
//  Vipect_Example
//
//  Created by Saul Moreno Abril on 23/12/20.
//  Copyright © 2020 CocoaPods. All rights reserved.
//

import UIKit
import Vipect

//MARK: SimpleView Class
final class SimpleView: UserInterface {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.title = "Simple modal view"
        view.backgroundColor = .yellow
        
        let label = UILabel()
        label.text = "This simple module is generated by code, no storyboard, nibs or swift ui"
        label.textColor = .black
        label.font = .systemFont(ofSize: 22, weight: .bold)
        label.numberOfLines = 0
        label.frame = view.frame.insetBy(dx: 20, dy: 20)
        view.addSubview(label)
    }
}

//MARK: - SimpleView API
extension SimpleView: SimpleViewApi {
}

// MARK: - SimpleView Viper Components API
private extension SimpleView {
    var presenter: SimplePresenterApi {
        return _presenter as! SimplePresenterApi
    }
}
