name: Test Pod

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    name: Tests
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['/Applications/Xcode_12.2.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 100
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }} # change your gemfile path
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle Install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build and test
        run: bundle exec fastlane test
      - name: Run danger
        run: |
          bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.ACCESS_TOKEN }}
